# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  codecov: codecov/codecov@1.0.2
  python: circleci/python@1.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    parameters:
      publish_pypi:
        type: string
        default: ""
    steps:
      - checkout
      - run:
          name: Retrieve Kafka C Handler
          command: |
            git clone https://github.com/edenhill/librdkafka.git
            cd librdkafka && ./configure --prefix /usr && make && sudo make install
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests and Run Coverage
          command: |
              pip install coverage
              coverage run -m unittest tests/all_tests.py
              coverage xml
      - codecov/upload:
          file: './coverage.xml'
          token: $CODECOV_TOKEN
      - when:
          condition: <<parameters.publish_pypi>>
          steps:
            - run:
                name: Pubish package
                command: |
                  python3 -m pip install --upgrade build
                  pip3 install twine
                  python -m build
                   python3 -m twine upload dist/*
workflows:
  build_and_publish:
    jobs:
      - build